### **Data Collection: Data collection is defined as the procedure of collecting, measuring and analyzing accurate insights for research using standard validated techniques. A researcher can evaluate their hypothesis on the basis of collected data. In most cases, data collection is the primary and most important step for research, irrespective of the field of research. The approach of data collection is different for different fields of study, depending on the required information.**

### **The most critical objective of data collection is ensuring that information-rich and reliable data is collected for statistical analysis so that data-driven decisions can be made for research.**

# **Data Collection and Datasets**
1.   From .csv Files
2.   From Excel Files
3.   From SQL Files

**Create the csv ,excel and sql database and table for storing the following data. Also load and display the data from all these sources into Google colab notebook**.

In [ ]:
%cd ..
from google.colab import drive
drive.mount('/content/gdrive')

/
Mounted at /content/gdrive

Unzip dataset.zip and extract all files

In [ ]:
#Unzipping dataset
dir=""
import zipfile
zip_ref=zipfile.ZipFile("/content/gdrive/MyDrive/datasets.zip","r")
zip_ref.extractall(dir)
zip_ref.close()

FileNotFoundError: ignored

**TASK 1-Loading data from csv file**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#importing numpy library
import numpy
#importing pandas library
import pandas as pd
#Defining path of csv file
location="/content/drive/MyDrive/FDS/dataset/smallgradesh.csv"
open(location).read()

In [ ]:
#Displaying data of .csv file without header
df=pd.read_csv(location,header=None)
df

In [ ]:

#Display first five lines of data
df.head()

In [ ]:
#loading data from CSV file and adding header
location="/content/drive/MyDrive/FDS/dataset/smallgradesh.csv"

#To add headers as we load
df=pd.read_csv(location,names=['Names','Grades'])
#To add headers to dataframe
df.columns=['Names','Grades']
df.head()

**SAVING DATA TO CSV**

While doing analysis, you can save your progress into a file

In [ ]:
#Exporting a dataset to CSV
import pandas as pd
names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
GradeList=zip(names,grades)
df=pd.DataFrame(data=GradeList,columns=['Names','Grades'])
df.to_csv('studentgradesA.csv',index=False,header=False)
df

In [ ]:
import pandas as pd
names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
bsdeg=[1,1,0,0,1]
msdeg=[2,1,0,0,0]
phd=[0,1,0,0,0]
GradeList=zip(names,grades,bsdeg,msdeg,phd)
df=pd.DataFrame(data=GradeList,columns=['Names','Grades','BS','MS','Phd'])
df.to_csv('studentgrades.csv',index=False,header=False)
df


**Task 2-Loading data from excel files**

In [ ]:
import pandas as pd
location="/content/drive/MyDrive/FDS/dataset/gradedata.csv"
df= pd.read_csv(location)

#Changing column name
df.columns=['first','last','sex','age','exer','hrs','grd','addr']
df.head()

**Saving data to excel file**

In [ ]:
pip install xlsxwriter

In [ ]:
import pandas as pd
names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
GradeList=zip(names,grades)
df=pd.DataFrame(data=GradeList,columns=['Names','Grades'])
writer=pd.ExcelWriter('dataframe.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet1')
writer.save()
Location="/content/drive/MyDrive/FDS/dataset/gradedata.csv"
df=pd.read_excel(Location)
df.head()

**TASK-3 Loading data from SQL**

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
#Connect to sqlite db
db_file=r'datasets/gradedata.db'
engine=create_engine(r"sqlite:///{}".format(db_file))
sql='SELECT * from test where Grades in (76,77,78)'
sales_data_df = pd.read_sql(sql,engine)
sales_data_df

**Saving data to SQL**

In [ ]:

names=['Bob','Jessica','Mary','John','Mel']
grades=[76,95,77,78,99]
GradeList=zip(names,grades)
df=pd.DataFrame(data=GradeList,columns=['names','Grades'])
df

In [ ]:
import os
import sqlite3 as lite
db_filename=r'mydb.db'
con=lite.connect(db_filename)
df.to_sql('mytable',
          con,
          schema=None,
          if_exists='replace',
          index=True,
          index_label=None,
          chunksize=None,
          dtype=None
          )
con.close()

In [ ]:
from pandas import DataFrame
Cars={'Brand':['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
      'Price':[22000,25000,27000,35000]
      }
df=DataFrame(Cars,columns=['Brand','Price'])
print(df)

In [ ]:

import sqlite3


**Create db named 'TestDB1.db'**

In [ ]:

conn=sqlite3.connect('TestDB1.db')
c=conn.cursor()

**Create the 'CARS' table**

In [ ]:

c.execute('CREATE TABLE CARS (Brand text, Price number)')
conn.commit()

use the following syantx to get from pands DataFrame to **SQL**

In [ ]:
df.to_sql('CARS',conn,if_exists='replace',index=False)


**create db named 'TESTDB2.db'**

In [ ]:

conn=sqlite3.connect('TestDB2.db')
c=conn.cursor()
c.execute('CREATE TABLE CARS (Brand text, Price number)')
conn.commit()

In [ ]:
Cars={'Brand':['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
      'Price':[22000,25000,27000,35000]
      }
df=DataFrame(Cars,columns=['Brand','Price'])
print(df)

In [ ]:

df.to_sql('CARS',conn,if_exists='replace',index=False)

**find the maximum price among all the brands**

In [ ]:

c.execute('''
SELECT Brand,max(Price) from CARS
''')

In [ ]:

df=DataFrame(c.fetchall(),columns=['Brand','Price'])
df

**Example1**

In [ ]:
 import pandas as pd
import os
import sqlite3 as lite
from sqlalchemy import create_engine
 
EmpId=["E101","E102","E103","E104"]
FName=["Shweta","Manisha","Madhu","Anita"]
LName=["Subnis","Perdesi","Mali","Rai"]
Designation=["ProjectEngineer","Tester","SrSoftwareEngineer","WebDeveloper"]
Basic_Salary=[40000,50000,60000,70000]
 
Empdata = zip(EmpId,FName,LName,Designation,Basic_Salary)
df = pd.DataFrame(data =Empdata, columns=['EmpId','FName','LName','Designation','Basic_Salary'])
df.to_csv('studentgrades.csv',index=False,header=False)
 
 
 
df
 
df1=df.to_csv('employeedata.csv',index=False,header=True)
 
df2=df.to_excel('employeedata2.xlsx',index=False,header=True)
 
db_filename = r'employee.db'
con = lite.connect(db_filename)
df.to_sql('employee',
con,
schema=None,
if_exists='replace',
index=True,
index_label=None,
chunksize=None,
dtype=None)
con.close()
 
dfcsv=pd.read_csv("employeedata.csv")
 
dfcsv
 
dfex=pd.read_excel("employeedata2.xlsx")
dfex
 
db_file = r'employee.db'
engine = create_engine(r"sqlite:///{}" .format(db_file))
sql = 'SELECT * from employee '
'where Basic_Salary in (40000,50000,60000,70000)'
empdf = pd.read_sql(sql, engine)
empdf

**Example 2**

In [ ]:
import pandas as pd 
import os
import sqlite3 as lite
from sqlalchemy import create_engine

studentId=["rj101","rj150","rj134","rj70"]
SName=["Saurabh","Giftson","Vikas","Radha"]
LName=["Chavan","Paul","Bisoi","Rai"]
Department=["Bms","Bcom","BscCS","BScIT"]
Email=["100rabh@gmail.com","gift01@gmail.com","vik21@gmail.com","rad01@gmail.com"]

studata = zip(studentId,SName,LName,Department,Email)
df = pd.DataFrame(data =studata, columns=['StudentId','SName','LName','Department','Email'])
df.to_csv('studentdata.csv',index=False,header=False)

df
df1=df.to_csv('studentdata.csv',index=False,header=True)
 
df2=df.to_excel('studentdata2.xlsx',index=False,header=True)
 
db_filename = r'studentdata.db'
con = lite.connect(db_filename)
df.to_sql('student',
con,
schema=None,
if_exists='replace',
index=True,
index_label=None,
chunksize=None,
dtype=None)
con.close()

dfcsv=pd.read_csv("studentdata.csv")
dfcsv


dfex=pd.read_excel("studentdata2.xlsx")
dfex

db_file = r'studentdata.db'
engine = create_engine(r"sqlite:///{}" .format(db_file))
sql = 'SELECT * from student '


studf = pd.read_sql(sql, engine)
studf

**Example 3**

In [ ]:

import pandas as pd 
import os
import sqlite3 as lite
from sqlalchemy import create_engine

sales_Representative=["sara","farahan","patrick","francheska","Henry","preson"]
Location=["New_York","Oregon","New_Jersy","New_York","Washington","Oregon"]
Region=["East","west","East","East","West","East"]
Customer=["Justin","Roy","Aian","Franklin","Danie","Phyllis"]
Item=["Watch","Mobile","Stationary","Jeans","Mobile","TV"]
Quantity=[2,1,15,2,1]
Price=[1000,25000,500,5750,10000,50000]

saledata = zip(sales_Representative,Location,Region,Customer,Item,Quantity,Price)
df = pd.DataFrame(data =saledata, columns=['sales_Representative','Location','Region','Customer','Item','Quantity','Price'])
df.to_csv('salestdata.csv',index=False,header=False)


df
df1=df.to_csv('sale1tdata.csv',index=False,header=True)
 
df2=df.to_excel('sale2.xlsx',index=False,header=True)
 
db_filename = r'salesmandata.db'
con = lite.connect(db_filename)
df.to_sql('salesman',
con,
schema=None,
if_exists='replace',
index=False,
index_label=None,
chunksize=None,
dtype=None)
con.close()

dfcsv=pd.read_csv("sale1tdata.csv")
dfcsv


dfex=pd.read_excel("sale2.xlsx")
dfex

db_file = r'salesmandata.db'
engine = create_engine(r"sqlite:///{}" .format(db_file))
sql = 'SELECT * from salesman '


saledf = pd.read_sql(sql, engine)
saledf

**Example 4**

In [ ]:
import pandas as pd 
import os
import sqlite3 as lite
from sqlalchemy import create_engine
  
# list of name, degree, score 
nme = ["aparna", "pankaj", "sudhir", "Geeku"] 
deg = ["MBA", "BCA", "M.Tech", "MBA"] 
scr = [90, 40, 80, 98] 
  
# dictionary of lists  
dict = {'name': nme, 'degree': deg, 'score': scr}  
    
df = pd.DataFrame(dict) 
    
df  
df.to_csv('scoredata.csv',index=False,header=False)


df
df1=df.to_csv('scoredata1.csv',index=False,header=True)
 
df2=df.to_excel('scoredata2.xlsx',index=False,header=True)
 
db_filename = r'score.db'
con = lite.connect(db_filename)
df.to_sql('scoretable',
con,
schema=None,
if_exists='replace',
index=False,
index_label=None,
chunksize=None,
dtype=None)
con.close()

dfcsv=pd.read_csv("scoredata1.csv")
dfcsv


dfex=pd.read_excel("scoredata2.xlsx")
dfex

db_file = r'score.db'
engine = create_engine(r"sqlite:///{}" .format(db_file))
sql = 'SELECT * from scoretable where score is 90'


scoredf = pd.read_sql(sql, engine)
scoredf

**Example 5**

In [ ]:
import pandas as pd 
import os
import sqlite3 as lite
from sqlalchemy import create_engine

# Create two lists in Python
education = ["Bachelor's", "Less than Bachelor's",
             "Master's","PhD","Professional"]
salary = [110000,105000,126000,144200,96000]

# create a dictionary using lists
a_dict = {"Education":education,
                  "Salary":salary}

# Create a data frame using the dictionary
df = pd.DataFrame(a_dict)
df

df.to_csv('salarydata.csv',index=False,header=False)


df
df1=df.to_csv('salarydata1.csv',index=False,header=True)
 
df2=df.to_excel('salarydata2.xlsx',index=False,header=True)
 
db_filename = r'salary.db'
con = lite.connect(db_filename)
df.to_sql('salarytable',
con,
schema=None,
if_exists='replace',
index=False,
index_label=None,
chunksize=None,
dtype=None)
con.close()

dfcsv=pd.read_csv("salarydata1.csv")
dfcsv


dfex=pd.read_excel("salarydata2.xlsx")
dfex

db_file = r'salary.db'
engine = create_engine(r"sqlite:///{}" .format(db_file))
sql = 'SELECT * from salarytable where salary is 144200'


scoredf = pd.read_sql(sql, engine)
scoredf

### **Data Preprocessing: Data preprocessing is an important step in the data mining process. The phrase "garbage in, garbage out" is particularly applicable to data mining and machine learning projects. Data-gathering methods are often loosely controlled, resulting in out-of-range values (e.g., Income: −100), impossible data combinations (e.g., Sex: Male, Pregnant: Yes), and missing values, etc. Analyzing data that has not been carefully screened for such problems can produce misleading results. Thus, the representation and quality of data is first and foremost before running any analysis.[1] Often, data preprocessing is the most important phase of a machine learning project, especially in computational biology.**
### **If there is much irrelevant and redundant information present or noisy and unreliable data, then knowledge discovery during the training phase is more difficult. Data preparation and filtering steps can take considerable amount of processing time. Data preprocessing includes cleaning, Instance selection, normalization, transformation, feature extraction and selection, etc. The product of data preprocessing is the final training set.**

### **Data Transformation: Data transformation is the process of converting data from one format or structure into another format or structure. It is a fundamental aspect of most data integration and data management tasks such as data wrangling, data warehousing, data integration and application integration.**
### **Data transformation can be simple or complex based on the required changes to the data between the source (initial) data and the target (final) data. Data transformation is typically performed via a mixture of manual and automated steps. Tools and technologies used for data transformation can vary widely based on the format, structure, complexity, and volume of the data being transformed.**

# **Data Preprocessing (Data Preparation and Data Transformations)**

1.   Missing Values
2.   Group By 
3.   Merge
4.   Transform
5.   Apply

**Example 1**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
state=pd.read_csv("/content/gdrive/MyDrive/Dataset/state (1).csv")
state.head()

FileNotFoundError: ignored

In [ ]:
#apply
def some_func(x):
  return x*2
state.apply(some_func) #update each entry of dataframe without any loop
state.apply(lambda n: n*2) #lambda also works the same

NameError: ignored

In [ ]:
#transform
state.transform(func = lambda x : x * 10)

In [ ]:
#usinggroupby
mean_purchase =state.groupby('Abbreviation')["Murder.Rate"].mean().rename("User_mean").reset_index() 
print(mean_purchase)

In [ ]:
#usinmerge
mean_purchase =state.groupby('Abbreviation')["Murder.Rate"].mean().rename("User_mean").reset_index() 
print(mean_purchase)
mer=state.merge(mean_purchase)

In [ ]:
mer

In [ ]:
#checking for missing values
print(state.isnull().sum())

**Example 2**

In [ ]:

import pandas as pd
import numpy as np
cols=['col0', 'col1', 'col2', 'col3', 'col4']
rows=['row0', 'row1', 'row2', 'row3', 'row4']
data=np.random.randint(0, 100, size=(5,5))
df=pd.DataFrame(data, columns=cols, index=rows)
df.head()

      col0  col1  col2  col3  col4
row0    38    50    89    83    82
row1    51    12    64     4    36
row2    19     3    69     4    62
row3    24    11    84     3    42
row4    74    84    33    82    13

In [ ]:
df.iloc[4, 2]

33

dealing with 0 and NAN values

In [ ]:
df.iloc[3, 3]=0
df.iloc[1, 2]=np.nan
df.iloc[4, 0]=np.nan
df['col5']=0
df['col6']=np.nan
df.head()

      col0  col1  col2  col3  col4  col5  col6
row0  38.0    50  89.0    83    82     0   NaN
row1  51.0    12   NaN     4    36     0   NaN
row2  19.0     3  69.0     4    62     0   NaN
row3  24.0    11  84.0     0    42     0   NaN
row4   NaN    84  33.0    82    13     0   NaN

In [ ]:
#use all() method to select columns that don't have zero values
df.loc[:, df.all()]

      col0  col1  col2  col4  col6
row0  38.0    50  89.0    82   NaN
row1  51.0    12   NaN    36   NaN
row2  19.0     3  69.0    62   NaN
row3  24.0    11  84.0    42   NaN
row4   NaN    84  33.0    13   NaN

In [ ]:

#display column that have atleast one non zero value
df.loc[:, df.any()]

      col0  col1  col2  col3  col4
row0  38.0    50  89.0    83    82
row1  51.0    12   NaN     4    36
row2  19.0     3  69.0     4    62
row3  24.0    11  84.0     0    42
row4   NaN    84  33.0    82    13

In [ ]:

#select columns with any nan
df.loc[:,df.isnull().any()]

      col0  col2  col6
row0  38.0  89.0   NaN
row1  51.0   NaN   NaN
row2  19.0  69.0   NaN
row3  24.0  84.0   NaN
row4   NaN  33.0   NaN

In [ ]:

#select column withou nan
df.loc[:, df.notnull().all()]

      col1  col3  col4  col5
row0    50    83    82     0
row1    12     4    36     0
row2     3     4    62     0
row3    11     0    42     0
row4    84    82    13     0

In [ ]:
df.dropna(how="all", axis=1) #if all the values in columns are nan it will be dropped

      col0  col1  col2  col3  col4  col5
row0  38.0    50  89.0    83    82     0
row1  51.0    12   NaN     4    36     0
row2  19.0     3  69.0     4    62     0
row3  24.0    11  84.0     0    42     0
row4   NaN    84  33.0    82    13     0

In [ ]:
df.dropna(how="any", axis=1) #if all the values in row are nan it will be dropped

      col1  col3  col4  col5
row0    50    83    82     0
row1    12     4    36     0
row2     3     4    62     0
row3    11     0    42     0
row4    84    82    13     0

In [ ]:
#filling mean value at the place of nan value
df.fillna(df.mean())

      col0  col1   col2  col3  col4  col5  col6
row0  38.0    50  89.00    83    82     0   NaN
row1  51.0    12  68.75     4    36     0   NaN
row2  19.0     3  69.00     4    62     0   NaN
row3  24.0    11  84.00     0    42     0   NaN
row4  33.0    84  33.00    82    13     0   NaN

Transforming Dataframe

In [ ]:

def some_func(x):
  return x*2
df.apply(some_func) #update each entry of dataframe without any loop
df.apply(lambda n: n*2) #lambda also works the same

       col0  col1   col2  col3  col4  col5  col6
row0   76.0   100  178.0   166   164     0   NaN
row1  102.0    24    NaN     8    72     0   NaN
row2   38.0     6  138.0     8   124     0   NaN
row3   48.0    22  168.0     0    84     0   NaN
row4    NaN   168   66.0   164    26     0   NaN

In [ ]:
#these function do not return the transformation so we have to store it explicitly
df['new_col']=df['col4'].apply(lambda n: n*2)
df.head()

      col0  col1  col2  col3  col4  col5  col6  new_col
row0  38.0    50  89.0    83    82     0   NaN      164
row1  51.0    12   NaN     4    36     0   NaN       72
row2  19.0     3  69.0     4    62     0   NaN      124
row3  24.0    11  84.0     0    42     0   NaN       84
row4   NaN    84  33.0    82    13     0   NaN       26

In [ ]:
#Transforming function in Python
import pandas as pd
import numpy as np
#creating a dataframe
df=pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
#applying the transform function
df.transform(func = lambda x : x * 10)

    a   b   c
0  10  20  30
1  40  50  60
2  70  80  90

In [ ]:
#Demonstrate transfomr function using pandas in python
import pandas as pd
import numpy as np
import random
data = pd.DataFrame({
    'C' : [random.choice(('a','b','c')) for i in range(1000000)],
    'A' : [random.randint(1,10) for i in range(1000000)],
    'B' : [random.randint(1,10) for i in range(1000000)]

})
data

        C  A   B
0       b  8   3
1       b  8   4
2       a  3   5
3       b  6   6
4       c  4  10
...    .. ..  ..
999995  c  6   9
999996  c  2   8
999997  b  8   6
999998  b  1  10
999999  c  6  10

[1000000 rows x 3 columns]

In [ ]:
#use the merge procedure
data.groupby('C')["A"].mean()
mean =data.groupby('C')["A"].mean().rename("N").reset_index()
df_1 = data.merge(mean)

In [ ]:
data['N3'] = data.groupby(['C'])['A'].transform('mean')

In [ ]:
#with apply() function

df['d'] = df.apply(lambda row: row.a + row.b + row.c, axis=1)

**Example 3**

In [ ]:
import pandas as pd
import numpy as np
Airline=pd.read_csv("/content/gdrive/MyDrive/FDS/dataset/airline_stats.csv")
Airline.head()

   pct_carrier_delay  pct_atc_delay  pct_weather_delay   airline
0           8.153226       1.971774           0.762097  American
1           5.959924       3.706107           1.585878  American
2           7.157270       2.706231           2.026706  American
3          12.100000      11.033333           0.000000  American
4           7.333333       3.365591           1.774194  American

**cheaking missing values**

In [ ]:
#cheaking missing values
print(Airline.isnull().sum())

pct_carrier_delay    28
pct_atc_delay        28
pct_weather_delay    28
airline               0
dtype: int64

In [ ]:
Airline.fillna(Airline.mean(), inplace=True)
Airline.isnull().sum()

pct_carrier_delay    0
pct_atc_delay        0
pct_weather_delay    0
airline              0
dtype: int64

**Groupby**

In [ ]:
mean_purchase =Airline.groupby('pct_atc_delay')["pct_weather_delay"].mean().rename("User").reset_index() 
print(mean_purchase)

       pct_atc_delay      User
0           0.000000  0.318154
1           0.005747  0.000000
2           0.013889  0.000000
3           0.014925  0.000000
4           0.016129  0.322581
...              ...       ...
26227      53.162791  0.000000
26228      54.838710  0.000000
26229      57.952381  0.109890
26230      60.000000  0.000000
26231     100.000000  0.000000

[26232 rows x 2 columns]

**Merge**

In [ ]:
mean_purchase =Airline.groupby('pct_atc_delay')["pct_weather_delay"].mean().rename("User").reset_index() 
print(mean_purchase)
df = Airline.merge(mean_purchase)
df

       pct_atc_delay      User
0           0.000000  0.318154
1           0.005747  0.000000
2           0.013889  0.000000
3           0.014925  0.000000
4           0.016129  0.322581
...              ...       ...
26227      53.162791  0.000000
26228      54.838710  0.000000
26229      57.952381  0.109890
26230      60.000000  0.000000
26231     100.000000  0.000000

[26232 rows x 2 columns]

       pct_carrier_delay  pct_atc_delay  pct_weather_delay    airline      User
0               8.153226       1.971774           0.762097   American  0.762097
1               5.959924       3.706107           1.585878   American  1.585878
2               7.157270       2.706231           2.026706   American  2.026706
3              12.100000      11.033333           0.000000   American  0.000000
4               7.333333       3.365591           1.774194   American  1.774194
...                  ...            ...                ...        ...       ...
33463           6.186422       8.798491           1.651940  Southwest  1.651940
33464           9.522167       3.591133           0.261084  Southwest  0.261084
33465           9.164179       2.664179           0.343284  Southwest  0.343284
33466           5.152293       1.964520           0.122817  Southwest  0.122817
33467           3.964393       1.700479           0.019449  Southwest  0.019449

[33468 rows x 5 columns]

**Transform**

In [ ]:
#applying the transform function
Airline.transform( lambda x : x * 10 )

       pct_carrier_delay  ...                                            airline
0              81.532258  ...  AmericanAmericanAmericanAmericanAmericanAmeric...
1              59.599237  ...  AmericanAmericanAmericanAmericanAmericanAmeric...
2              71.572700  ...  AmericanAmericanAmericanAmericanAmericanAmeric...
3             121.000000  ...  AmericanAmericanAmericanAmericanAmericanAmeric...
4              73.333333  ...  AmericanAmericanAmericanAmericanAmericanAmeric...
...                  ...  ...                                                ...
33463          61.864224  ...  SouthwestSouthwestSouthwestSouthwestSouthwestS...
33464          95.221675  ...  SouthwestSouthwestSouthwestSouthwestSouthwestS...
33465          91.641791  ...  SouthwestSouthwestSouthwestSouthwestSouthwestS...
33466          51.522926  ...  SouthwestSouthwestSouthwestSouthwestSouthwestS...
33467          39.643926  ...  SouthwestSouthwestSouthwestSouthwestSouthwestS...

[33468 rows x 4 columns]

**Apply**

In [ ]:

#applying the apply function
Airline.apply(lambda n: n *2,axis=1)

       pct_carrier_delay  pct_atc_delay  pct_weather_delay             airline
0              16.306452       3.943548           1.524194    AmericanAmerican
1              11.919847       7.412214           3.171756    AmericanAmerican
2              14.314540       5.412463           4.053412    AmericanAmerican
3              24.200000      22.066667           0.000000    AmericanAmerican
4              14.666667       6.731183           3.548387    AmericanAmerican
...                  ...            ...                ...                 ...
33463          12.372845      17.596983           3.303879  SouthwestSouthwest
33464          19.044335       7.182266           0.522167  SouthwestSouthwest
33465          18.328358       5.328358           0.686567  SouthwestSouthwest
33466          10.304585       3.929039           0.245633  SouthwestSouthwest
33467           7.928785       3.400958           0.038899  SouthwestSouthwest

[33468 rows x 4 columns]

**Example 4**

In [ ]:
import pandas as pd
import numpy as np

state=pd.read_csv("/content/County_Zhvi_AllHomes.csv")
state.head()

**Checking missing values**

In [ ]:
print(state.isnull().sum())

In [ ]:
state.fillna(state.mean,inplace=True)

In [ ]:
print(state.isnull().sum())

**groupby**

In [ ]:
mean_county =state.groupby('StateCodeFIPS')["MunicipalCodeFIPS"].mean().rename("User_mean").reset_index() 
print(mean_county)

**Transform and apply function**

In [ ]:
#applying the transform function
print(state.transform(lambda x : x * 10))

#applying the apply function
print(state.apply(lambda n:n*2,axis=1))

**merge**

In [ ]:
mean_county =state.groupby('StateCodeFIPS')["MunicipalCodeFIPS"].mean().rename("User_mean").reset_index() 
print(mean_county)
Ma=state.merge(mean_county)

In [ ]:
Ma

**Example 5**

In [ ]:
import pandas as pd
import numpy as np

loan=pd.read_csv("/content/loan_data.csv")
loan.head()

**checking missing values**

In [ ]:
print(state.isnull().sum())

**Groupby**

In [ ]:
mean_county =state.groupby('loan_amnt')["dti"].mean().rename("dti1").reset_index() 
print(mean_county)

 **Transform**

In [ ]:
#applying the transform function
print(state.transform(lambda x : x * 10))

**Apply**

In [ ]:
#applying the apply function
print(state.apply(lambda n:n*2,axis=1))

**merge**

In [ ]:
mean_county =state.groupby('annual_inc')["dti"].mean().rename("dti1").reset_index() 
print(mean_county)
mer=state.merge(mean_county)

In [ ]:
mer

**merge example 1**

In [ ]:

# Python program to merge 
# dataframes using Panda 
  
# Dataframe created 
left = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'], 
                    'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3']}) 
  
right = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'], 
                      'C': ['C0', 'C1', 'C2', 'C3'], 
                      'D': ['D0', 'D1', 'D2', 'D3']}) 
                        
# Merging the dataframes                       
pd.merge(left, right, how ='inner', on ='Key')

**Merge example 2**

In [ ]:
import pandas as pd
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame({
	'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print(pd.merge(left,right,on='id'))

**merge example 3**

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)

df3 = pd.merge(df1, df2)
df3